import type { Metadata } from "next";
import "@/app/index.css";
import { Box } from "@mui/material";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Playtube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Box bgcolor={"#000"}>
          <NavBar />
          {children}
        </Box>
      </body>
    </html>
  );
}
